### PR TITLE
fix UTF16 BOM removal problem on ruby 1.9.2

### PR DESCRIPTION
**Pull request by trampoline**
hi ping,

here's a fix for the problem with the BOM removal regexp on ruby 1.9.2

it's tested on both

ruby-1.9.2-p180 [ x86_64 ]
ruby-1.8.7-p334 [ x86_64 ]

against an Exchange 2010 SP1 server with NTLM authentication

it seems there are further problems with the ntlm_http.rb on ruby 1.9.2, but i authenticated fine using latest httpclient and 'net/ntlm' portion of pyu-ntlm-http gem, so i will raise another bug for the other problems

### CODE REVIEW

**Comment by lxcid** [comment]
This fix my problem. Thanks.

**Comment by ramonpin** [comment]
Same problem under Linux. This could be a good merge. Thx.

**Comment by lxcid** [comment]
I had fork the repo @ http://github.com/lxcid/ntlm-http that is bundler friendly.

Just have the following line in your Gemfile

```
gem "pyu-ntlm-http", :git => "git://github.com/lxcid/ntlm-http.git", :branch =>"1.9_utf16_bom_fix"
```

**Comment by ramonpin** [comment]
Thx Stan... really a great work with this gem.

**Comment by unimatrixZxero** [comment]
Stan's fix worked fine for me too. THX

**Comment by mmmries** [comment]
This fix worked for me on jruby-1.7.0 and mri-1.9.3-p286.  I'm pointing to the fork mentioned above until this gets merged and released to the gem.

**Pull request merged**
