### PR TITLE
Unify gemspecs

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Opening this PR to ask what's going on. This gem has two versions:

https://rubygems.org/gems/ntlm-http/

and 

https://rubygems.org/gems/pyu-ntlm-http/

The second one seems to be the right one that includes all the latest code, although it has a weird name.

However, `mechanize`, this gem's main dependant, uses the first one, which only has a single very old release.

@pyu10055 Can you clarify a bit? Thanks!

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Pinging also @mmmries as the last contributor, who actually added the current gemspec.

**Comment by mmmries** [comment]
Oh man, 2013 contributions FTW. I don't remember anything specific about that contribution, but it sounds like unifying the two gems would be beneficial for the community

**Comment by deivid-rodriguez** [comment]
Yeah, I know... :sweat_smile:. This is a very old unmaintained gem, but it's a dependency of a fairly popular one, `mechanize`, so it's still frequently used.

Your contribution is from 6 years old, but the latest release of `pyu-ntlm-http` is from 8 years ago, and the latest release of `ntml-http` (which mechanize is using) is from 2009! :grimacing:

**Comment by flavorjones** [comment]
Side note: next version of Mechanize will depend on `rubyntlm`.

**Pull request closed without merging**
